#!/bin/bash

# Google Ads Credential Diagnostic Script
# Run this to verify your Google Ads setup

echo "🔍 Google Ads Setup Diagnostic"
echo "================================"
echo ""

# Check if Railway CLI is available
if ! command -v railway &> /dev/null; then
    echo "⚠️  Railway CLI not installed. Checking with curl instead..."
    echo ""
fi

echo "📋 Required Environment Variables:"
echo ""
echo "These should be set in Railway → Variables:"
echo ""
echo "1. GOOGLE_ADS_CLIENT_ID"
echo "   Format: xxx.apps.googleusercontent.com"
echo "   Get from: Google Cloud Console → APIs → Credentials"
echo ""
echo "2. GOOGLE_ADS_CLIENT_SECRET"
echo "   Format: GOCSPX-xxxxxxxxxxxxx"
echo "   Get from: Same as CLIENT_ID"
echo ""
echo "3. GOOGLE_ADS_DEVELOPER_TOKEN"
echo "   Format: xxxxxxxxxxxxxxxxxxxx"
echo "   Get from: Google Ads → Tools → API Center"
echo "   ⚠️  MUST be approved by Google (can take 24-48 hours)"
echo ""
echo "4. GOOGLE_ADS_CUSTOMER_ID"
echo "   Format: 1234567890 (10 digits, NO DASHES)"
echo "   Get from: Google Ads top bar (shows as 123-456-7890)"
echo "   ⚠️  REMOVE DASHES when setting in Railway!"
echo ""
echo "5. GOOGLE_ADS_REFRESH_TOKEN"
echo "   Format: 1//xxxxxxxxxxxxx"
echo "   Get from: OAuth2 flow (see instructions below)"
echo ""
echo "================================"
echo ""
echo "🔧 Common Issues & Fixes:"
echo ""
echo "Issue 1: Customer ID has dashes"
echo "  ❌ Wrong: 123-456-7890"
echo "  ✅ Right: 1234567890"
echo ""
echo "Issue 2: Developer token not approved"
echo "  Solution: Apply at Google Ads → Tools → API Center"
echo "  Timeline: 24-48 hours for approval"
echo "  Workaround: Use test account (instant approval)"
echo ""
echo "Issue 3: Missing OAuth scopes"
echo "  Required scope: https://www.googleapis.com/auth/adwords"
echo "  Fix: Regenerate refresh token with correct scope"
echo ""
echo "Issue 4: API not enabled"
echo "  Fix: Google Cloud Console → APIs → Enable 'Google Ads API'"
echo ""
echo "================================"
echo ""
echo "🚀 Quick Test:"
echo ""
echo "Run this command to test your credentials:"
echo ""
echo "curl -X POST https://api.arbi.creai.dev/api/marketplace/list \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{
    \"opportunityId\": \"test-ads-verify\",
    \"productTitle\": \"Test Product for Ads\",
    \"productDescription\": \"Testing Google Ads integration\",
    \"supplierPrice\": 100,
    \"supplierUrl\": \"https://amazon.com/test\",
    \"supplierPlatform\": \"amazon\"
  }'"
echo ""
echo "Look for:"
echo "  ✅ Real campaign ID (numeric): Campaign created successfully"
echo "  ❌ Simulated ID (google_timestamp_random): API failed, check logs"
echo ""
echo "================================"
echo ""
echo "📖 How to Get Refresh Token:"
echo ""
echo "1. Install Google Ads API client:"
echo "   npm install -g google-ads-api"
echo ""
echo "2. Run OAuth flow:"
echo "   google-ads generateRefreshToken"
echo ""
echo "3. Follow prompts, authorize app"
echo ""
echo "4. Copy refresh token to Railway Variables"
echo ""
echo "================================"
echo ""
echo "💡 FASTEST SOLUTION: Use Google Ads Test Account"
echo ""
echo "Instead of waiting for developer token approval:"
echo ""
echo "1. Create test Google Ads account"
echo "2. Go to: https://ads.google.com/aw/test-accounts"
echo "3. Create test account (instant approval)"
echo "4. Use test account credentials"
echo "5. Test campaigns won't spend real money"
echo "6. Switch to production when approved"
echo ""
echo "================================"
echo ""
echo "Need help? Check Railway logs:"
echo "railway logs --service api | grep 'Google Ads'"
echo ""
