packages:
  - 'apps/*'
  - 'packages/ai-engine'
  - 'packages/arbitrage-engine'
  - 'packages/data'
  - 'packages/eslint-config'
  - 'packages/transaction'
  - 'packages/tsconfig'
  - 'packages/voice-interface'
  - 'packages/web-automation'
